[package]
name = "hpke-boringssl-bindgen"
version = "0.1.0"
edition = "2024"

[dependencies]
bindgen = "0.71.1"
syn = { version = "2.0.100", default-features = false, features = ["visit", "visit-mut"] }
quote = "1.0.40"
proc-macro2 = "1.0.94"
prettyplease = "0.2.31"
heck = "0.5.0"